spring.application.name=SpringSecurity

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=TRACE

jwt.secret=
jwt.issuer= sangs
jwt.expiry=3600


#Google Oauth2 / OIDC
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email
